jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: my_password  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "This is my test"
  test:
    docker:
      - image: circleci/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: my_password  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "This is my second test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test